version: '3'

x-airflow-common:
  &airflow-common
  env_file: ./.env
  volumes:
    - airflow_dags:/opt/airflow/dags
    - airflow_logs:/opt/airflow/logs

services:
  api:
    container_name: air-api
    user: 1000:1000
    image: kboiiz/air-quality-api:latest
    command: ./startup.sh
    ports:
      - 8100:8100
    env_file: ./.env
    depends_on:
      postgres:
        condition: service_healthy

  app:
    profiles: ["air_app", "full", "deploy", "test"]
    container_name: app
    user: 1000:1000
    build: ./services/frontend
    environment:
      - NODE_ENV=production
    command: node serveApp.js
    ports:
      - 9000:9000
    volumes:
      - ./services/frontend/:/app
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: kboiiz/air-quality-postgres:latest
    environment:
      POSTGRES_MULTIPLE_DATABASES: "air_quality,airflow"
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 15s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    user: 1000:1000
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

volumes:
  postgres-db-volume:
  airflow_dags:
  airflow_logs:
