[tool.black]
line-length = 88

[tool.pytest.ini_options]
env = [
    "AIRFLOW_UID=1000",
    "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow",
    "AIRFLOW__CORE__EXECUTOR=CeleryExecutor",
    "AIRNOW_API_KEY=AA5AB45D-9E64-41DE-A918-14578B9AC816",
    "DEV_MODE=true",
    "POSTGRES_USER=airflow",
    "POSTGRES_PASSWORD=airflow",
    "POSTGRES_DB=airflow",
    "POSTGRES_URI=postgresql://airflow:airflow@postgres:5432/air_quality",
    "SQLALCHEMY_DATABASE_URI=postgresql://airflow:airflow@postgres:5432/airflow",
    "WAQI_BASE_URL=https://api.waqi.info/",
    "WAQI_TOKEN=bb10d851797e497b46823a5b4f984354c6ff4d9a"
]