#!/bin/bash

set -e

echo "Creating airflow db and user"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE ROLE $POSTGRES_AIRFLOW_USER WITH SUPERUSER LOGIN PASSWORD '$POSTGRES_AIRFLOW_USER_PW';
	ALTER USER $POSTGRES_AIRFLOW_USER SET search_path = public;
	CREATE DATABASE airflow;
	GRANT ALL PRIVILEGES ON DATABASE airflow TO $POSTGRES_AIRFLOW_USER;
EOSQL

echo "Creating air_quality db and user"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER $POSTGRES_AIR_QUALITY_USER WITH PASSWORD '$POSTGRES_AIR_QUALITY_USER_PW';
	CREATE DATABASE air_quality;
	GRANT ALL PRIVILEGES ON DATABASE air_quality TO $POSTGRES_AIR_QUALITY_USER;
EOSQL