# syntax=docker/dockerfile:1

FROM postgis/postgis:15-3.3

COPY create_dev_db.sh /docker-entrypoint-initdb.d/

COPY dump/air_quality_dev_dump.sql /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/air_quality_dev_dump.sql
RUN chmod +x /docker-entrypoint-initdb.d/create_dev_db.sh

EXPOSE 5432
