"""adding station_id to airnow tables

Revision ID: 135782bddaf4
Revises: c1fb85880d50
Create Date: 2023-02-03 20:03:39.936272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135782bddaf4'
down_revision = 'c1fb85880d50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings_waqi_temp',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('pm_10', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('pm_25', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('co', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('h', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('no2', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('o3', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('p', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('so2', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('t', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('w', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('wg', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('reading_datetime', sa.DateTime(), nullable=False),
    sa.Column('request_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('station_id', 'reading_datetime')
    )
    op.create_table('stations_waqi_temp',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('request_datetime', sa.DateTime(), nullable=True),
    sa.Column('data_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.drop_table('spatial_ref_sys')
    op.add_column('readings_airnow', sa.Column('station_id', sa.Integer(), nullable=False))
    op.add_column('readings_airnow', sa.Column('pm_10_AQI', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('readings_airnow', sa.Column('pm_10_AQI_CAT', sa.Numeric(precision=2, scale=1), nullable=True))
    op.add_column('readings_airnow', sa.Column('pm_25_AQI', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('readings_airnow', sa.Column('pm_25_AQI_CAT', sa.Numeric(precision=2, scale=1), nullable=True))
    op.drop_column('readings_airnow', 'pm_25_aqi_cat')
    op.drop_column('readings_airnow', 'pm_10_aqi_cat')
    op.drop_column('readings_airnow', 'pm_25_aqi')
    op.drop_column('readings_airnow', 'pm_10_aqi')
    op.add_column('readings_waqi', sa.Column('station_id', sa.Integer(), nullable=False))
    op.add_column('stations_airnow', sa.Column('station_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations_airnow', 'station_id')
    op.drop_column('readings_waqi', 'station_id')
    op.add_column('readings_airnow', sa.Column('pm_10_aqi', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True))
    op.add_column('readings_airnow', sa.Column('pm_25_aqi', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True))
    op.add_column('readings_airnow', sa.Column('pm_10_aqi_cat', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True))
    op.add_column('readings_airnow', sa.Column('pm_25_aqi_cat', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True))
    op.drop_column('readings_airnow', 'pm_25_AQI_CAT')
    op.drop_column('readings_airnow', 'pm_25_AQI')
    op.drop_column('readings_airnow', 'pm_10_AQI_CAT')
    op.drop_column('readings_airnow', 'pm_10_AQI')
    op.drop_column('readings_airnow', 'station_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('stations_waqi_temp')
    op.drop_table('readings_waqi_temp')
    # ### end Alembic commands ###
