"""drop waqi

Revision ID: b43de609a6c1
Revises: 59e28f048844
Create Date: 2023-02-16 13:31:07.819584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b43de609a6c1'
down_revision = '59e28f048844'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations_waqi')
    op.drop_table('stations_waqi_temp')
    op.drop_table('readings_waqi_temp')
    op.drop_table('readings_waqi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'stations_airnow', sa.Column('country', sa.VARCHAR(), nullable=True)
        )
    op.alter_column(
        'stations_airnow', 'status', existing_type=sa.VARCHAR(), nullable=False
        )
    op.drop_column('stations_airnow', 'country_fips')
    op.create_table(
        'readings_waqi',
        sa.Column(
            'station_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('station_name', sa.VARCHAR(), nullable=False),
        sa.Column(
            'reading_datetime',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False),
        sa.Column('request_datetime', postgresql.TIMESTAMP(), nullable=False),
        sa.Column('latitude', sa.NUMERIC(10, 6), nullable=True),
        sa.Column('longitude', sa.NUMERIC(10, 6), nullable=True),
        sa.Column('pm_10', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('pm_25', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('co', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('h', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('no2', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('o3', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('p', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('so2', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('t', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('w', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('wg', sa.NUMERIC(7, 3), nullable=True),
        sa.PrimaryKeyConstraint(
            'station_id', 'reading_datetime', name='readings_waqi_pkey'
            )
    )
    op.create_table(
        'readings_waqi_temp', sa.Column(
            'station_id', sa.INTEGER(), autoincrement=False, nullable=False
            ),
        sa.Column('station_name', sa.VARCHAR(), nullable=False),
        sa.Column('latitude', sa.NUMERIC(10, 6), nullable=True),
        sa.Column('longitude', sa.NUMERIC(10, 6), nullable=True),
        sa.Column('pm_10', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('pm_25', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('co', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('h', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('no2', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('o3', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('p', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('so2', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('t', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('w', sa.NUMERIC(7, 3), nullable=True),
        sa.Column('wg', sa.NUMERIC(7, 3), nullable=True),
        sa.Column(
            'reading_datetime',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False
            ),
        sa.Column('request_datetime', postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint(
            'station_id', 'reading_datetime', name='readings_waqi_temp_pkey'
            )
    )
    op.create_table('stations_waqi_temp',
        sa.Column('station_id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('latitude', sa.NUMERIC(10, 6), autoincrement=False, nullable=False),
        sa.Column('longitude', sa.NUMERIC(10, 6), autoincrement=False, nullable=False),
        sa.Column('request_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('data_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('station_id', name='stations_waqi_temp_pkey')
    )
    op.create_table('stations_waqi',
        sa.Column('station_id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('latitude', sa.NUMERIC(10, 6), autoincrement=False, nullable=False),
        sa.Column('longitude', sa.NUMERIC(10, 6), autoincrement=False, nullable=False),
        sa.Column('request_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('data_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('station_id', name='stations_waqi_pkey')
    )
    op.create_table('spatial_ref_sys',
        sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
        sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
