"""adding foreign keys

Revision ID: d5c893d58579
Revises: 55036a2dee06
Create Date: 2023-02-06 01:28:00.332048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5c893d58579'
down_revision = '55036a2dee06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings_waqi_temp')
    op.drop_table('readings_airnow_temp')
    op.drop_table('readings_airnow')
    op.drop_table('stations_waqi_temp')
    op.drop_table('readings_waqi')
    op.drop_table('spatial_ref_sys')
    op.drop_index('idx_stations_airnow_location_coord', table_name='stations_airnow')
    op.drop_table('stations_airnow')
    op.drop_index('idx_stations_airnow_temp_location_coord', table_name='stations_airnow_temp')
    op.drop_table('stations_airnow_temp')
    op.drop_table('stations_waqi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations_waqi',
    sa.Column('station_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('request_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('station_id', name='stations_waqi_pkey')
    )
    op.create_table('stations_airnow_temp',
    sa.Column('station_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agency_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('location_coord', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('station_id', name='stations_airnow_temp_pkey')
    )
    op.create_index('idx_stations_airnow_temp_location_coord', 'stations_airnow_temp', ['location_coord'], unique=False)
    op.create_table('stations_airnow',
    sa.Column('station_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agency_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('location_coord', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('station_id', name='stations_airnow_pkey')
    )
    op.create_index('idx_stations_airnow_location_coord', 'stations_airnow', ['location_coord'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('readings_waqi',
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reading_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('request_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('pm_10', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('pm_25', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('co', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('h', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('no2', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('o3', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('p', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('so2', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('t', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('w', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('wg', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('station_id', 'reading_datetime', name='readings_waqi_pkey')
    )
    op.create_table('stations_waqi_temp',
    sa.Column('station_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('request_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('station_id', name='stations_waqi_temp_pkey')
    )
    op.create_table('readings_airnow',
    sa.Column('station_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reading_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('request_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pm_10_conc', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('pm_10_aqi', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('pm_10_aqi_cat', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('pm_25_conc', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('pm_25_aqi', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('pm_25_aqi_cat', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('station_id', 'reading_datetime', name='readings_airnow_pkey')
    )
    op.create_table('readings_airnow_temp',
    sa.Column('station_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reading_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('request_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pm_10_conc', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('pm_10_aqi', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('pm_10_aqi_cat', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('pm_25_conc', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('pm_25_aqi', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('pm_25_aqi_cat', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('station_id', 'reading_datetime', name='readings_airnow_temp_pkey')
    )
    op.create_table('readings_waqi_temp',
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reading_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('request_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('pm_10', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('pm_25', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('co', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('h', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('no2', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('o3', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('p', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('so2', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('t', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('w', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.Column('wg', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('station_id', 'reading_datetime', name='readings_waqi_temp_pkey')
    )
    # ### end Alembic commands ###
